config/routes.rb
Rails.application.routes.draw do
  

  root 'drawings#index'
  
  get 'static_pages/home' => 'static_pages#home'
  
  match '/approve', to: 'users#approve', via: 'post'
  
  devise_for :users
  
  resources :drawings
  resources :users do
      resources :drawings
  end
  


   #, :controllers => { :registrations => "users/registrations" } #  users/registrations_controller.rb
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/drawing.rb
class Drawing < ApplicationRecord
  belongs_to :user
  mount_uploader :attachment, DrawingUploader
  default_scope -> { order(updated_at: :desc) }
  
  validates :title, presence: true, length: { maximum: 80 }
  validates :attachment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :drawings, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
         
  def active_for_authentication? 
    super && approved?
  end 

  def inactive_message 
    if !confirmed? && !approved?
      :not_confirmed_nor_approved
    elsif !approved?
      :not_approved 
    else 
      super # Use whatever other message 
    end 
  end
  
  def approve!
    update_attribute(:approved, true)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def logged_in_user
    unless user_signed_in?
      flash[:danger] = "Proszę się zalogować"
      redirect_to new_user_session_path
    end
  end

 protected

 def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
 end
end

app/controllers/drawings_controller.rb
class DrawingsController < ApplicationController
    before_action :set_drawing, only: [:edit, :update, :destroy]
    before_action :authenticate_user!, only: [:edit, :update, :destroy, :new, :create]
    respond_to :html, :js
    
    def index
        if params[:user]
            @user = User.find(params[:user][:id])
            @drawings = @user.drawings.page(params[:page]).per(10)
        else
            @drawings = Drawing.page(params[:page]).per(10)
            @latest_id = @drawings.first.id
        end
    end
    
    def show
        @id = params[:id].to_i
        @drawing = Drawing.find(@id)
        @prev = Drawing.where('id = ?', (@id - 1).to_s).select([:id]).first
        @next = Drawing.where('id = ?', (@id + 1).to_s).select([:id]).first
        @nav = {:prev => @prev, :next => @next}
    end
    
    def new
        @drawing = Drawing.new
    end
    
    def create
        @user = current_user
        @drawing = @user.drawings.create(drawing_params)
        
        if @drawing.save
            flash[:success] = "New drawing added."
            redirect_to @drawing
        else
            render 'new'
        end
    end
    
    def edit
        
    end
    
    def destroy
        if @drawing.destroy
            flash[:success] = "Drawing deleted."
            redirect_to drawings_url
        else
            flash[:danger] = "Problem with deleting."
        end
    end
    
    def update
        if @drawing.update_attributes(drawing_params)
            flash[:success] = "Drawing updated."
            redirect_to @drawing
        else
            flash[:danger] = "Incorrect attributes."
            redirect_to edit_drawing_url
        end
    end
    
    private
        def set_drawing
            @drawing = Drawing.find(params[:id])
        end

    # Never trust parameters from the scary internet, only allow the white list through.
        def drawing_params
            params.require(:drawing).permit(:title, :attachment, :program)
        end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  protected
    def after_inactive_sign_up_path_for(resource)
      root_url# Or :prefix_to_your_route
    end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:approve, :show, :edit, :update]
  
  def index
    if current_user && current_user.admin?
      @users = User.where("confirmed_at IS NOT NULL")
      flash[:danger] = "Users list is only available to admin users"
      redirect_to root_url
    end
  end
  
  def show
  end
  
  def edit
  end
  
  def update
    if @user.id == current_user.id
      if @user.save
        flash[:success] = "Profile updated"
      else
        flash[:danger] = "Not updated"
      end
    end
  end
  
  def approve
    if current_user && current_user.admin?
      @user.approve!
    end
  end
  
  
  private
    def set_user
      @user = User.find(params[:id])
    end
    
    def user_params
      params.require(:user).permit(:name, :email, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drawings_helper.rb
module DrawingsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/drawings/_drawing.html.haml
%li{:id => ("latest" if drawing.id == @latest_id)}
    .drawing-container{ id: ( "single-drawing" if (controller.action_name != "index") ) }
        -if drawing.id == @latest_id
            %p= "Latest drawing"
        .drawing-image
            -if drawing.attachment.present?
                -if controller.action_name == "index"
                    = link_to drawing, :class => "pull-left" do
                        = image_tag drawing.attachment_url(:thumb), :class => "drawing-image"
                -elsif controller.action_name == "show"
                    %img{:src => drawing.attachment_url}
        .drawing-info
            %p= drawing.title
            -if drawing.program.present?
                %p.program Created in: #{drawing.program}
        - if current_user && (drawing.user_id == current_user.id)
            .drawing-actions
                = link_to edit_drawing_path(drawing), { title: t('shared.edit') } do
                    %button.btn.btn-default
                        = fa_icon "pencil"
                = link_to edit_drawing_path(drawing), { title: t('shared.delete') } do
                    %button.btn.btn-default
                        = fa_icon "trash"
    .nav-prev
        -if defined? nav
            -unless nav[:prev].nil?
                = link_to drawing_path(nav[:prev]), { title: t('shared.prev') } do
                    %button.btn.btn-default
                        = fa_icon "backward"
            -else 
                %button.btn.btn-default
                    = fa_icon "times"
    .nav-next
        -if defined? nav
            -unless nav[:next].nil?
                = link_to drawing_path(nav[:next]), { title: t('shared.next') } do
                    %button.btn.btn-default
                        = fa_icon "forward"
            -else 
                %button.btn.btn-default
                    = fa_icon "times"

app/views/drawings/_form.html.erb
<%= form_for @drawing do |f| %>
    <%= render 'shared/error_messages', object: @drawing %>
    
    <%= f.label :title %>
    <%= f.text_field :title %>
    <br>
    
    <%= f.label :program %>
    <%= f.text_field :program %>
    <br>
    
    <%= f.label :attachment %>
    <%= f.file_field :attachment %>
    
    <%= f.submit "Save", class: "btn btn-primary" %>

<% end %>

app/views/drawings/edit.html.haml
- provide(:title, 'Edit')
%h1 Edit
.col-md-6.col-md-offset-3
    = render 'form'

app/views/drawings/index.html.haml
%ul.drawings
    =render @drawings, locals: {:latest_id => @latest_id}
    =paginate @drawings

app/views/drawings/new.html.haml
- provide(:title, 'New drawing')
%h1 New drawing
.col-md-6.col-md-offset-3
    = render 'form'

app/views/drawings/show.html.haml
- provide(:title, @drawing.title)
.drawing-list
    %ul.drawing
        = render @drawing, nav: @nav

app/views/layouts/_header.html.haml
%header.main-navbar-header
    .container
        .row
            .navbar-header.inline-block
                = link_to "Portfolio", root_path, id: "logo"
            .main-navbar.navbar-header.main-buttons
                .nav.inline-block.margin-15px-fixed
                    %ul.navlist
                        %li
                            .dropdown
                                %button.dropdown-toggle.action-button.shadow.animate.red{:type => "button", "data-toggle" => "dropdown"} Drawings
                                %ul.dropdown-menu
                                    %li= link_to "All drawings", drawings_path
                                    - if user_signed_in?
                                        %li= link_to "My drawings", user_drawings_path(current_user)
                                        %li= link_to "Add new drawing", new_drawing_path
                        - if user_signed_in?
                            %li= link_to "Profile", user_path(current_user.id), class: "action-button shadow animate red"
                            %li= link_to "Users", users_path, class: "action-button shadow animate red"
                            %li= link_to "Log out", destroy_user_session_path, method: "delete", class: "action-button shadow animate red"
                        - else
                            %li= link_to "Log in", new_user_session_path, class: "action-button shadow animate red"
                            %li= link_to "Create account", new_user_registration_path, class: "action-button shadow animate red"
            .hamburger-menu
                %button.navbar-toggle.collapsed.hamburger{:type => "button", "data-target" => "#navbar-collapse", "data-toggle" => "collapse"}
                    %span.sr-only Toggle navigation
                    %span.icon-bar
                    %span.icon-bar
                    %span.icon-bar
                .collapse.navbar-collapse.hamburger#navbar-collapse
                    %ul.side-menu
                        %li= link_to "All drawings", drawings_path
                        - if user_signed_in?
                            %li= link_to "My drawings", user_drawings_path(current_user)
                            %li= link_to "Add new drawing", new_drawing_path
                            %li= link_to "Profile", "#"
                            %li= link_to "Users", users_path
                            %li= link_to "Log out", destroy_user_session_path, method: "delete"
                        - else
                            %li= link_to "Log in", new_user_session_path
                            %li= link_to "Create account", new_user_registration_path
            
                        

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gallery</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <div id="main-container">
      <%= render 'layouts/header' %>
      <div id="flash-messages">
        <% flash.each do |key, value| %>
          <%= content_tag :div, value, :class => "flash #{key}" unless value.blank? %>
        <% end %>
      </div>
      <%= yield %>
    </div>
    <div class="clear-both"></div>
    
  </body>
</html>

app/views/layouts/main.html.erb
<div class="grid">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h1>Strona główna</h1>
        </div>
    </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<h1>Main page</h1>
<p>This will be the main page of the site</p>

app/views/users/_user.html.haml
%tr
    %td= user.name
    %td= user.email
    - if user.approved?
        %td= "User approved"
        %td= ""
    - else
        %td= "User not approved"
        %td= link_to "Approve this user", approve_path(:id => user.id), method: :post

app/views/users/index.html.haml
%table.table.table-condensed.display.responsive.no-wrap#users_datatable
    %thead
        %tr
            %th= t('user.columns.name')
            %th= t('user.columns.email')
            %th= t('user.columns.approved')
            %th= "Action"
    %tbody
        = render @users